name: econ
channels:
  - pytorch
  - nvidia
  - conda-forge
  - fvcore
  - iopath
  - bottler
  - defaults
dependencies:
  - python=3.8
  - pytorch-cuda=11.6
  - pytorch=1.13.0
  - nvidiacub
  - torchvision
  - fvcore
  - iopath
  - pyembree
  - cupy
  - cython
  - pip