name: econ-if
ckpt_dir: "./data/ckpt/"
normal_path: "./data/ckpt/normal/last.ckpt"
ifnet_path: "./data/ckpt/IF-Geo/last-128.ckpt"
# ifnet_path: "./data/ckpt/IF-Geo/last-128-nobody.ckpt"
results_path: "./results"

net:
  in_nml: (('image',3), ('T_normal_F',3), ('T_normal_B',3))
  in_geo: (('normal_F',3), ('normal_B',3))

dataset:
  prior_type: "SMPL"

test_mode: True
batch_size: 1

# user defined
vol_res: 256      # IF-Net volume resolution
mcube_res: 256
clean_mesh: True  # if True, will remove floating pieces
cloth_overlap_thres: 0.50
body_overlap_thres: 0.93

# bni:
#   k: 2
#   lambda1: 1e-3
#   boundary_consist: 1e-5

bni:
  k: 4
  lambda1: 1e-4
  boundary_consist: 1e-6
  poisson_depth: 10
  # use_smpl: ["hand", "face"]
  use_smpl: []
  always_ifnet: True
  use_poisson: False
  hand_thres: 4e-2
  face_thres: 6e-2
  thickness: 0.02
  hps_type: "pixie"
  finish: False
